version: "3.8"

services:

  #db:
  #  container_name: db_container
  #  image: postgres:13.1-alpine
  #  volumes:
  #    - ./app/database:/var/lib/postgresql/data
  #    - ./app/initdb:/docker-entrypoint-initdb.d
  #  environment:
  #    - POSTGRES_DB=${DB_NAME}
  #    - POSTGRES_USER=${DB_USER}
  #    - POSTGRES_PASSWORD=${DB_PASSWORD}
  #  ports:
  #    - ${DB_PORTS}

  backend:
    container_name: backend_container
    build:
      context: .
      dockerfile: DockerfileBackend
      target: dev
    volumes:
      - ./app/backend/:/go/
    ports:
      - "8080:8080"

  frontend:
    container_name: frontend_container
    build:
      context: .
      dockerfile: DockerfileFrontend
    volumes:
      - ./app/frontend:/dockerFrontend
      - build_folder:/dockerFrontend/build
    ports:
      - "3000:3000"

  nginx:
    container_name: nginx_container
    build:
      context: .
      dockerfile: DockerfileNginx
    volumes:
      - build_folder:/var/www/
    ports:
      - "80:80"
    depends_on:
      - frontend

volumes:
  build_folder: